import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";

import "@/app/globals.css";
import Navbar from "@/components/educator/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/educator/Footer";
import Sidebar from "@/components/educator/Sidebar";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
});

export const metadata: Metadata = {
  title: "Ascend Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bricolage.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-(--font-bricolage)">
        <ClerkProvider>
          <Navbar />
          <section className="min-h-screen bg-white flex">
            <Sidebar />

            <main className="flex-1 p-6">{children}</main>
          </section>
          <Footer />
        </ClerkProvider>
      </body>
    </html>
  );
}
