import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";

import "@/app/globals.css";
import Navbar from "@/components/student/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { Course } from "@/types/course";
import { getCourses } from "@/lib/getCourses";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
});

export const metadata: Metadata = {
  title: "Ascend Academy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const allCourses: Course[] = await getCourses();

  return (
    <html lang="en" className={`${bricolage.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-(--font-bricolage)">
        <ClerkProvider>
          <Navbar allCourses={allCourses} />
          <main className="flex-1">{children}</main>
          <Toaster position="top-right" />
        </ClerkProvider>
      </body>
    </html>
  );
}
