import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";

import "@/app/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/educator/Footer";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/educator/AppSidebar";
import { Toaster } from "@/components/ui/sonner";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
});

export const metadata: Metadata = {
  title: "Ascend Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bricolage.variable} h-full antialiased`}>
      <body className="min-h-screen font-(--font-bricolage)">
        <ClerkProvider>
          <SidebarProvider>
            <AppSidebar />

            <SidebarInset>
              {/* Top Bar */}
              <div className="sticky top-0 z-40 flex h-16 items-center border-b bg-white px-6">
                <SidebarTrigger />
              </div>

              {/* Page Content */}
              <div>{children}</div>

              <Toaster position="top-right" />

              <Footer />
            </SidebarInset>
          </SidebarProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
